export const CONTAINER_PADDING_X = 16;

export const POPUP_SIDE_OFFSET = 5;
export const POPUP_SIDE_OFFSET_WITH_ARROW = 10;
export const POPUP_ARROW_PADDING = 10;
export const POPUP_COLLISION_PADDING_BLOCK = 5;
export const POPUP_COLLISION_PADDING_INLINE = CONTAINER_PADDING_X;
